export const pricingPlans = {
   monthly: [
      {
         id: 'basic',
         title: 'Basic Plan',
         desc: 'Access to a curated selection of abstract images',
         price: '$9.99',
         period: '/ month',
         billing: 'Billed monthly',
         features: ['Standard quality images', 'Limited to personal use', 'Email support'],
      },
      {
         id: 'standard',
         popular: true,
         title: 'Standard Plan',
         desc: 'Next-level integrations, priced economically',
         price: '$19.99',
         period: '/ month',
         billing: 'Billed monthly',
         features: [
            'Expanded library',
            'High-resolution images',
            'Commercial use',
            'Priority support',
            'Advanced analytics',
         ],
      },
      {
         id: 'premium',
         title: 'Premium Plan',
         desc: 'Experience limitless living for power users',
         price: '$29.99',
         period: '/ month',
         billing: 'Billed monthly',
         features: [
            'Full image library',
            'Premium collections',
            'Resale rights',
            'Dedicated support',
            '24/7 response',
         ],
      },
   ],

   yearly: [
      {
         id: 'basic',
         title: 'Basic Plan',
         desc: 'Access to a curated selection of abstract images',
         price: '$99',
         period: '/ year',
         billing: 'Billed yearly',
         features: ['Standard quality images', 'Limited to personal use', 'Email support'],
      },
      {
         id: 'standard',
         popular: true,
         title: 'Standard Plan',
         desc: 'Next-level integrations, priced economically',
         price: '$199',
         period: '/ year',
         billing: 'Billed yearly',
         features: [
            'Expanded library',
            'High-resolution images',
            'Commercial use',
            'Priority support',
            'Advanced analytics',
         ],
      },
      {
         id: 'premium',
         title: 'Premium Plan',
         desc: 'Experience limitless living for power users',
         price: '$299',
         period: '/ year',
         billing: 'Billed yearly',
         features: [
            'Full image library',
            'Premium collections',
            'Resale rights',
            'Dedicated support',
            '24/7 response',
         ],
      },
   ],
};
